default_language_version:
  python: python3


ci:
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit suggestions"
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: check-added-large-files
        args: ["--maxkb=100", "--enforce-all"]
      - id: detect-private-key

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: ["--write-changes"]
        exclude: pyproject.toml

  - repo: https://github.com/crate-ci/typos
    rev: v1.20.7
    hooks:
      - id: typos
        args: []
        exclude: pyproject.toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      # try to fix what is possible
      - id: ruff
        args: ["--fix"]
      # perform formatting updates
      - id: ruff-format
      # validate if all is fine with preview mode
      - id: ruff

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 1.7.0
    hooks:
      - id: pyproject-fmt
        additional_dependencies: [tox]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.16
    hooks:
      - id: validate-pyproject
