# Deploy container image to Cloud Run
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run',
    'deploy',
    '$_MODEL_NAME',
    '--image',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/example-mlops-containers/app',
    '--region',
    'europe-west1',
    '--platform',
    'managed',
    '--allow-unauthenticated',
    '--set-env-vars=MODEL_CHECKPOINT=$_MODEL_CHECKPOINT',
    '--set-env-vars=WANDB_API_KEY=$$WANDB_API_KEY',
    '--set-env-vars=WANDB_ENTITY=$$WANDB_ENTITY',
    '--set-env-vars=WANDB_PROJECT=$$WANDB_PROJECT',
  ]
  secretEnv: ['WANDB_API_KEY', 'WANDB_ENTITY', 'WANDB_PROJECT']

substitutions:
  _MODEL_NAME: 'app'
  _MODEL_CHECKPOINT: 'models/checkpoint.onnx'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/WANDB_API_KEY
    env: 'WANDB_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/WANDB_ENTITY
    env: 'WANDB_ENTITY'
  - versionName: projects/$PROJECT_ID/secrets/WANDB_PROJECT
    env: 'WANDB_PROJECT'
options:
  logging: CLOUD_LOGGING_ONLY
