defaults:
  - common

model_checkpoint: ???  # Path to the model checkpoint needs to be provided
logdir: null  # null correspond to default hydra config

experiment_logger:
  project: "example_mlops_project"
  entity: "best_mlops_team"
  job_type: "evaluate"
  save_code: True

datamodule:
  _target_: "example_mlops.data.MnistDataModule"
  data_dir: "data"
  batch_size: 128

external_data:
  name: "EMNIST"
  batch_size: 128
  config:
    _target_: "torchvision.datasets.EMNIST"
    root: "data/external"
    split: "digits"
    train: False
    download: True
    transform:
      _target_: "torchvision.transforms.v2.Compose"
      transforms:
        - _target_: "torchvision.transforms.v2.ToTensor"
        - _target_: "torchvision.transforms.v2.RGB"
