defaults:
  - common

model_checkpoint: ???  # Path to the model checkpoint

datamodule:
  _target_: "example_mlops.data.MnistDataModule"
  data_dir: "data"
  batch_size: 128

external_data:
  name: "EMNIST"
  batch_size: 128
  config:
    _target_: "torchvision.datasets.EMNIST"
    root: "data/external"
    split: "digits"
    train: False
    download: True
    transform:
      _target_: "torchvision.transforms.v2.Compose"
      transforms:
        - _target_: "torchvision.transforms.v2.ToTensor"
        - _target_: "torchvision.transforms.v2.RGB"
