defaults:
  - common

logdir: null  # null correspond to default hydra config
train: True
evaluate: True
upload_model: True

model:
  _target_: "example_mlops.model.MnistClassifier"
  backbone: "resnet18"

datamodule:
  _target_: "example_mlops.data.MnistDataModule"
  data_dir: "data"
  val_split: 0.1
  batch_size: 128
  num_workers: 0
  pin_memory: True

experiment_logger:
  _target_: "pytorch_lightning.loggers.WandbLogger"
  project: "example_mlops_project"
  entity: "best_mlops_team"
  job_type: "train"
  save_code: True

callbacks:
  early_stopping:
    _target_: "pytorch_lightning.callbacks.EarlyStopping"
    monitor: "val_loss"
    mode: "min"
    patience: 5
    verbose: True
  checkpoint:
    _target_: "pytorch_lightning.callbacks.ModelCheckpoint"
    monitor: "val_loss"
    mode: "min"
    save_last: True
    save_top_k: 3
    dirpath: "checkpoints"
    filename: "{epoch:02d}-{val_loss:.2f}"
  learning_rate_monitor:
    _target_: "pytorch_lightning.callbacks.LearningRateMonitor"
    logging_interval: "epoch"
  progress_bar:
    _target_: "pytorch_lightning.callbacks.RichProgressBar"

trainer:
  accelerator: "auto"
  max_epochs: 20
  gradient_clip_val: 0.0
