# Deploy container image to Cloud Run
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    '$_MODEL_NAME',
    '--image',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/example-mlops-containers/app',
    '--region',
    'europe-west1',
    '--platform',
    'managed',
    '--memory=1024Mi',
    '--set-env-vars=MODEL_CHECKPOINT=$_MODEL_CHECKPOINT',
    '--set-env-vars=LOG_LEVEL=DEBUG',
    '--update-secrets=WANDB_API_KEY=WANDB_API_KEY:latest',
    '--update-secrets=WANDB_ENTITY=WANDB_ENTITY:latest',
    '--update-secrets=WANDB_PROJECT=WANDB_PROJECT:latest',
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Set IAM Policy to allow all users to invoke the service'
  waitFor: ['Deploy to Cloud Run']
  args: [
    'run',
    'services',
    'add-iam-policy-binding',
    '--region=europe-west1',
    '--member=allUsers',
    '--role=roles/run.invoker',
    '$_MODEL_NAME',
  ]

substitutions:
  _MODEL_NAME: 'app'
  _MODEL_CHECKPOINT: 'models/checkpoint.onnx'

options:
  logging: CLOUD_LOGGING_ONLY
