name: Deploy production model

on:
  repository_dispatch:
    types: deploy_model
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Model artifact to be deployed'
        required: true
        type: string

jobs:
  identify_event:
    runs-on: ubuntu-latest
    outputs:
      model_name: ${{ steps.set_output.outputs.model_name }}
    steps:
      - name: Check event type
        run: |
          if [ -n "${{ github.event.client_payload }}" ]; then
            echo "Event type: repository_dispatch"
            echo "Payload Data: ${{ toJson(github.event.client_payload) }}"
          elif [ -n "${{ github.event.inputs }}" ]; then
            echo "This is a workflow dispatch event"
            # Access input parameters if needed
            echo "Input Parameters: ${{ toJson(github.event.inputs) }}"
          else
            echo "Unknown event type"
          fi

  deploy_production_model:
    runs-on: ubuntu-latest
    needs: identify_event
    env:
      MODEL_NAME: ${{ needs.identify_event.outputs.model_name }}
    steps:
      - name: Echo model name
        run: |
          echo "Model name: $MODEL_NAME"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          make dev_requirements
          pip list

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy model
        run: |
          gcloud builds submit --config cloudbuild_deploy_model.yaml \
            --substitutions=_MODEL_NAME="production-model",_MODEL_CHECKPOINT=$MODEL_NAME
