name: Deploy production model

on:
  repository_dispatch:
    types: deploy_model
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Model artifact to production workflow'
        required: true
        type: string

jobs:
  identify_event:
    runs-on: ubuntu-latest
    outputs:
      model_name: ${{ steps.set_output.outputs.model_name }}
    steps:
      - name: Check event type
        run: |
          if [ -n "${{ github.event.client_payload }}" ]; then
            echo "Event type: repository_dispatch"
            echo "Payload Data: ${{ toJson(github.event.client_payload) }}"
          elif [ -n "${{ github.event.inputs }}" ]; then
            echo "This is a workflow dispatch event"
            # Access input parameters if needed
            echo "Input Parameters: ${{ toJson(github.event.inputs) }}"
          else
            echo "Unknown event type"
          fi

      - name: Setting model environment variable and output
        id: set_output
        run: |
          if [ -n "${{ github.event.client_payload }}" ]; then
            echo "model_name=${{ github.event.client_payload.artifact_version_string }}" >> $GITHUB_OUTPUT
          elif [ -n "${{ github.event.inputs }}" ]; then
            echo "model_name=${{ github.event.inputs.model_name }}" >> $GITHUB_OUTPUT
          fi

  deploy_production_model:
    runs-on: ubuntu-latest
    needs: identify_event
    env:
      MODEL_NAME: ${{ needs.identify_event.outputs.model_name }}
    steps:
      - name: Echo model name
        run: |
          echo "Model name: $MODEL_NAME"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          make dev_requirements
          pip list

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy model
        run: |
          gcloud builds submit \
            --config gcp/cloudbuild_deploy_model.yaml \
            --substitutions=_MODEL_NAME="production-model",_MODEL_CHECKPOINT=$MODEL_NAME

  loadtest_production_model:
    runs-on: ubuntu-latest
    needs: deploy_production_model
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          make dev_requirements
          pip list

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Extract deployed model URL
        run: |
          DEPLOYED_MODEL_URL=$(gcloud run services describe production-model \
            --region=europe-west1 \
            --format='value(status.url)')
          echo "DEPLOYED_MODEL_URL=$DEPLOYED_MODEL_URL" >> $GITHUB_ENV

      - name: Run load test on deployed model
        env:
          DEPLOYED_MODEL_URL: ${{ env.DEPLOYED_MODEL_URL }}
        run: |
          locust -f tests/performance/locustfile.py \
            --headless -u 100 -r 10 --run-time 10m --host=$DEPLOYED_MODEL_URL
