name: Deploy production model

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy_model:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.head.ref, 'deploy_model')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Submit build
        run: |
