name: Check staged model

on:
  repository_dispatch:
    types: staged_model
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Model artifact to optimize and convert'
        required: true
        type: string

jobs:
  identify_event:
    runs-on: ubuntu-latest
    outputs:
      model_name: ${{ steps.set_output.outputs.model_name }}
    steps:
      - name: Check event type
        run: |
          if [ -n "${{ github.event.client_payload }}" ]; then
            echo "Event type: repository_dispatch"
            echo "Payload Data: ${{ toJson(github.event.client_payload) }}"
          elif [ -n "${{ github.event.inputs }}" ]; then
            echo "This is a workflow dispatch event"
            # Access input parameters if needed
            echo "Input Parameters: ${{ toJson(github.event.inputs) }}"
          else
            echo "Unknown event type"
          fi

      - name: Setting model environment variable and output
        id: set_output
        run: |
          if [ -n "${{ github.event.client_payload }}" ]; then
            echo "model_name=${{ github.event.client_payload.artifact_version_string }}" >> $GITHUB_OUTPUT
          elif [ -n "${{ github.event.inputs }}" ]; then
            echo "model_name=${{ github.event.inputs.model_name }}" >> $GITHUB_OUTPUT
          fi

  evaluate_model:
    runs-on: ubuntu-latest
    needs: identify_event
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      WANDB_ENTITY: ${{ secrets.WANDB_ENTITY }}
      WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}
      MODEL_NAME: ${{ needs.identify_event.outputs.model_name }}
    steps:
      - name: Echo model name
        run: |
          echo "Model name: $MODEL_NAME"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          make dev_requirements
          pip list

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Pull data
        run: |
          dvc pull --no-run-cache
          python -c "from pathlib import Path; print([str(file) for file in Path('data').rglob('*') if file.is_file()])"

      - name: Evaluate model
        run: evaluate model_checkpoint=$MODEL_NAME

      - name: Convert to ONNX and quantize
        run: model_management export-and-quantize $MODEL_NAME

      - name: Evaluate quantized model
        run: evaluate model_checkpoint=models/checkpoint_quantized.onnx upload_model=True

      - name: Link quantized model to model registry
        run: model_management link-latest-model mnist_model -a pre-production

      - name: Upload artifacts for future jobs
        uses: actions/upload-artifact@v2
        with:
          name: models
          path: models/

  inference_tests:
    runs-on: ubuntu-latest
    needs: evaluate_model
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: models
          path: models/

      - name: List downloaded artifacts
        run: ls -l models

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          make dev_requirements
          pip list

      - name: Run performance check on model
        env:
          MODEL_TO_TEST: models/checkpoint.ckpt
        run: pytest tests/performance

      - name: Run performance check on quantized model
        env:
          MODEL_TO_TEST: models/checkpoint_quantized.onnx
        run: pytest tests/performance

      - name: Compare performance metrics
        run: pytest-benchmark compare --sort name --group name

  deploy_staged_model:
    runs-on: ubuntu-latest
    needs: inference_tests
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      WANDB_ENTITY: ${{ secrets.WANDB_ENTITY }}
      WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          make dev_requirements
          pip list

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get model id of quantized model
        run: |
          echo "MODEL_NAME=$(model_management print_latest_model mnist_model)" >> $GITHUB_ENV

      - name: Deploy model
        env:
          MODEL_NAME: ${{ env.MODEL_NAME }}
        run: |
          gcloud builds submit --config cloudbuild_deploy_model.yaml \
            --substitutions=_MODEL_NAME="staged-model-{{ env.MODEL_NAME }}", _MODEL_CHECKPOINT={{ env.MODEL_NAME }}

  loadtest_deployed_model:
    runs-on: ubuntu-latest
    needs: deploy_staged_model
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      WANDB_ENTITY: ${{ secrets.WANDB_ENTITY }}
      WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          make dev_requirements
          pip list

      - name: Get model id of quantized model
        run: |
          echo "MODEL_NAME=$(model_management print_latest_model mnist_model)" >> $GITHUB_ENV

      - name: Extract deployed model URL
        env:
          MODEL_NAME: ${{ env.MODEL_NAME }}
        run: |
          DEPLOYED_MODEL_URL=$(gcloud run services describe staged-model-${{ env.MODEL_NAME }} --format='value(status.url)')
          echo "DEPLOYED_MODEL_URL=$DEPLOYED_MODEL_URL" >> $GITHUB_ENV

      - name: Run load test on deployed model
        env:
          DEPLOYED_MODEL_URL: ${{ env.DEPLOYED_MODEL_URL }}
        run: locust -f tests/performance/locustfile.py --headless -u 100 -r 10 --run-time 1m --host=$DEPLOYED_MODEL_URL
