name: Test workflow

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Model artifact to optimize and convert'
        required: true
        type: string

jobs:
  testcase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.16.1/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Simulate changes to config file
        env:
          MODEL_NAME: ${{ github.event.inputs.model_name }}
        run:
          yq eval ".model.checkpoint = \"${MODEL_NAME}\"" -i configs/app.yaml

      - name: Verify changes
        run: cat configs/app.yaml

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Create CML PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          cml pr create configs/app.yaml --title "Model checkpoint updated" --body "Updated model checkpoint to ${MODEL_NAME}"
